trigger:
- main

variables:
  azureSubscription: 'AzureSubscription'  # Azure DevOps のサービスコネクション名
  appName: 'sample-sidecar'
  resourceGroup: 'yuka_rg_0636'

pool:
  name: 'Default'

stages:
- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  jobs:
  - job: Deploy
    steps:
    - checkout: self
    - task: AzureWebAppContainer@1
      displayName: 'Deploy docker-compose to Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        resourceGroupName: $(resourceGroup)
        multicontainerConfigFile: docker-compose.yml
        multicontainerConfigType: 'compose'
